name: Daily URL Request

on:
  schedule:
    # Runs at 19:17 UTC every day (which is 20:17 in the UK during BST)
    - cron: '17 19 * * *'

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run request script
        run: python request_script.py
